Repository holoviz/panel, pull requests merged in 2019-11, with the labels that each got.

#744 Do not center responsive HoloViews content
  panel/pane/holoviews.py
Labels: type: enhancement

#745 Add support for jupyter_bokeh ipywidget rendering
  examples/user_guide/Deploy_and_Export.ipynb
  panel/__init__.py
  panel/config.py
  panel/io/__init__.py
  panel/io/notebook.py
  panel/viewable.py
Labels: type: enhancement

#747 Documentation metadata clearout
  examples/reference/panes/Markdown.ipynb
  examples/reference/panes/VTKVolume.ipynb
  examples/reference/widgets/DataFrame.ipynb
  examples/reference/widgets/FileInput.ipynb
  examples/reference/widgets/PasswordInput.ipynb
  examples/reference/widgets/Progress.ipynb
  examples/reference/widgets/TextAreaInput.ipynb
  examples/user_guide/Links.ipynb
  examples/user_guide/Param.ipynb
Labels: type: docs

#755 Improvements and fixes for ipywidget rendering
  examples/user_guide/Deploy_and_Export.ipynb
  panel/io/notebook.py
  panel/pane/base.py
  panel/pane/holoviews.py
  panel/tests/test_io.py
  panel/tests/test_viewable.py
  panel/viewable.py
  panel/widgets/base.py
  setup.py
Labels: type: bug

#756 Add Divider
  panel/layout.py
Labels: type: enhancement

#761 Ensure that GridBox does not distribute non-filled rows evenly
  panel/layout.py
  panel/tests/test_layout.py
Labels: type: bug

#771 Convert objects to panel before creating ipywidget
  panel/io/notebook.py
Labels: status: ready

#772 Ensure JS dist bundle is included in package
  MANIFEST.in
Labels: status: ready

#770 Make Pipeline graph clickable
  panel/pipeline.py
  panel/tests/test_pipeline.py
Labels: status: ready

#765 Expanded and updated FAQ
  doc/Comparisons.rst
  doc/FAQ.rst
Labels: type: docs

#774 Various Template improvements
  examples/assets/occupancy.csv
  panel/template.py
Labels: status: ready

#768 V0.7.0 doc updates
  doc/Comparisons.rst
  doc/FAQ.rst
  doc/_static/collage/attractors.png
  doc/_static/collage/eulers_method.png
  doc/_static/collage/gapminders.png
  doc/_static/collage/glaciers.png
  doc/_static/collage/interact.png
  doc/_static/collage/nyc_taxi.png
  doc/index.rst
  doc/user_guide/index.rst
  examples/gallery/demos/portfolio-optimizer.ipynb
  examples/getting_started/Introduction.ipynb
  examples/user_guide/Links.ipynb
  examples/user_guide/Overview.ipynb
  examples/user_guide/Param.ipynb
  examples/user_guide/Widgets.ipynb
  panel/param.py
  panel/tests/widgets/test_base.py
  panel/widgets/player.py
Labels: status: ready

#812 Fixed handling of state._views for Templates
  panel/template.py
Labels: type: bug
