Repository holoviz/panel, pull requests merged in 2019-12, with the labels that each got.

#854 Removed redundant Circle.__init__ from example.
  examples/gallery/param/param_subobjects.ipynb
Labels: status: ready, type: docs

#857 Unlock Document and dispatch events if we have lock
  panel/io/__init__.py
  panel/io/server.py
  panel/pane/base.py
  panel/pane/holoviews.py
  panel/viewable.py
  panel/widgets/base.py
Labels: type: enhancement

#869 Delay VTK namespace imports
  panel/models/vtk/vtk.ts
  panel/models/vtk/vtk_utils.ts
  panel/models/vtk/vtkaxes.ts
  panel/tests/pane/test_vega.py
Labels: type: bug

#881 Improve Markdown handling
  examples/reference/panes/Markdown.ipynb
  panel/_styles/markdown.css
  panel/pane/markup.py
  panel/tests/pane/test_base.py
  panel/tests/pane/test_markup.py
  panel/util.py
Labels: type: enhancement
