Repository holoviz/panel, pull requests merged in 2020-10, with the labels that each got.

#1513 Implementation of (Int|Float)[Input|Spinner] (New Bokeh widgets)
  examples/reference/widgets/FloatInput.ipynb
  examples/reference/widgets/IntInput.ipynb
  examples/reference/widgets/Spinner.ipynb
  panel/param.py
  panel/widgets/__init__.py
  panel/widgets/input.py
Labels: ready for review

#1535 Enhanced responsive grid template
  examples/assets/React.png
  examples/assets/ReactDark.png
  examples/reference/templates/React.ipynb
  panel/layout/grid.py
  panel/template/base.py
  panel/template/react/__init__.py
  panel/template/react/dark.css
  panel/template/react/default.css
  panel/template/react/react.css
  panel/template/react/react.html
  panel/tests/test_template.py
Labels: status: WIP

#1662 Material Template Fixes
  panel/template/__init__.py
  panel/template/material/__init__.py
  panel/template/material/material.css
  panel/template/material/material.html
  panel/template/theme.py
  panel/tests/template/test_manual.py
Labels: in progress

#1687 Dark Theme Scrollbar Fixes
  panel/template/bootstrap/dark.css
  panel/template/golden/dark.css
  panel/template/material/dark.css
  panel/template/react/dark.css
  panel/template/vanilla/dark.css
Labels: ready for review, status: ready, type: enhancement

#1685 Fix navigation issues
  panel/template/base.py
  panel/template/bootstrap/bootstrap.css
  panel/template/bootstrap/bootstrap.html
  panel/template/golden/golden.css
  panel/template/golden/golden.html
  panel/template/material/material.css
  panel/template/material/material.html
  panel/template/vanilla/vanilla.css
  panel/template/vanilla/vanilla.html
  panel/tests/template/test_manual.py
Labels: ready for review, status: ready, type: enhancement

#1691 Add support for Pyecharts
  examples/reference/panes/ECharts.ipynb
  panel/pane/echarts.py
  panel/tests/pane/test_echart.py
Labels: ready for review, status: ready

#1695 React Template Fixes
  panel/template/react/react.css
  panel/template/react/react.html
  panel/tests/template/test_manual.py
Labels: ready for review, status: ready

#1694 Enable specifying items on Template construction
  panel/template/base.py
  panel/tests/test_template.py
Labels: ready for review, status: ready

#1697 Add example to gallery
  examples/gallery/links/plotly_link.ipynb
  examples/gallery/links/vega_heatmap_link.ipynb
  examples/gallery/simple/defer_data_load.ipynb
  examples/gallery/simple/sync_location.ipynb
  examples/reference/panes/Video.ipynb
  panel/config.py
  panel/io/location.py
Labels: type: docs

#1698 Fix CSS load order in Templates
  panel/template/bootstrap/bootstrap.css
  panel/template/bootstrap/bootstrap.html
  panel/template/golden/golden.css
  panel/template/golden/golden.html
  panel/template/material/material.css
  panel/template/material/material.html
  panel/template/react/react.css
  panel/template/react/react.html
  panel/template/vanilla/vanilla.css
Labels: ready for review, status: ready
