Repository holoviz/panel, pull requests merged in 2020-03, with the labels that each got.

#1123 [VTKSlicer]fix bokeh hook function
  examples/gallery/demos/VTKSlicer.ipynb
Labels: status: ready

#1095 Made signature of show() match that of servable()
  panel/viewable.py
Labels: type: enhancement

#1140 Add MultiChoice widget
  examples/reference/widgets/MultiChoice.ipynb
  panel/tests/widgets/test_select.py
  panel/widgets/__init__.py
  panel/widgets/select.py
Labels: type: enhancement

#1156 Link to discourse rather than gitter.
  doc/index.rst
Labels: type: docs
