Repository holoviz/panel, pull requests merged in 2020-04, with the labels that each got.

#1190 Prepare for publishing package to npm registry
  .gitignore
  panel/.gitignore
  panel/package-lock.json
  panel/package.json
Labels: status: WIP

#1216 Do not process events related to fake Template root
  panel/io/state.py
  panel/layout.py
  panel/pane/base.py
  panel/template.py
  panel/viewable.py
  panel/widgets/base.py
Labels: type: bug

#1193 Fileupload with Pandas and Plotly example
  examples/gallery/param/download_upload_csv.ipynb
Labels: status: ready

#1226 Add API docs
  .travis.yml
  doc/api/index.rst
  doc/conf.py
  doc/generate_modules.py
  doc/index.rst
Labels: type: docs

#1239 Include panel/index.ts in package data
  MANIFEST.in
Labels: status: ready

#1262 Add Card and Accordion layout [doc-build]
  examples/reference/layouts/Accordion.ipynb
  examples/reference/layouts/Card.ipynb
  panel/__init__.py
  panel/_styles/card.css
  panel/layout.py
  panel/layout/__init__.py
  panel/layout/accordion.py
  panel/layout/base.py
  panel/layout/card.py
  panel/layout/grid.py
  panel/layout/spacer.py
  panel/layout/tabs.py
  panel/models/__init__.py
  panel/models/card.ts
  panel/models/index.ts
  panel/models/layout.py
  panel/tests/layout/__init__.py
  panel/tests/layout/test_accordion.py
  panel/tests/layout/test_base.py
  panel/tests/layout/test_card.py
  panel/tests/layout/test_grid.py
  panel/tests/layout/test_spacer.py
  panel/tests/layout/test_tabs.py
  panel/tests/test_layout.py
  panel/tests/utils.py
Labels: type: enhancement

#1308 Add missing property in WidgetBox docs
  examples/reference/layouts/WidgetBox.ipynb
Labels: type: docs
