Repository holoviz/panel, pull requests merged in 2020-11, with the labels that each got.

#1731 Updated documentation to pn.state.add_periodic_callback
  examples/gallery/simple/deckgl_game_of_life.ipynb
  examples/gallery/simple/random_number_generator.ipynb
  examples/reference/panes/Streamz.ipynb
Labels: type: docs

#1729 Fixes Alert c.f. #1728
  examples/reference/panes/Alert.ipynb
  panel/pane/alert.py
  panel/tests/pane/test_alert.py
Labels: ready for review, status: ready

#1748 Add DatetimeRangeInput widget
  examples/reference/widgets/DatetimeRangeInput.ipynb
  panel/tests/widgets/test_input.py
  panel/widgets/__init__.py
  panel/widgets/input.py
Labels: type: enhancement

#1743 Template Fixes - Mostly sidebar or main heights
  panel/template/bootstrap/bootstrap.css
  panel/template/bootstrap/bootstrap.html
  panel/template/react/react.css
  panel/template/vanilla/vanilla.css
Labels: ready for review, status: ready
