Repository holoviz/panel, pull requests merged in 2020-05, with the labels that each got.

#1328 Fixed jupyter-panel-proxy in Mybinder deployment
  examples/user_guide/Server_Deployment.ipynb
Labels: type: docs

#1344 Add Widget.from_param classmethod
  examples/user_guide/Param.ipynb
  panel/tests/widgets/test_base.py
  panel/widgets/base.py
Labels: type: enhancement

#1353 Player visual indicator of button pressed
  panel/models/player.ts
Labels: ready for review

#1361 download button fill the space
  panel/models/file_download.ts
Labels: ready for review

#1360 Player layout enhancements
  examples/reference/widgets/Player.ipynb
  panel/models/player.ts
  panel/models/widgets.py
  panel/widgets/player.py
Labels: ready for review

#1374 Ensure non-existent models in Template do not cause errors
  panel/template/base.py
Labels: type: bug
