Repository holoviz/panel, pull requests merged in 2020-06, with the labels that each got.

#1383 Add support for hierarchical multi-indexed DataFrame
  examples/reference/widgets/DataFrame.ipynb
  panel/tests/widgets/test_tables.py
  panel/widgets/tables.py
Labels: type: enhancement

#1248 VTK Synchronized
  examples/gallery/demos/VTKInteractive.ipynb
  examples/reference/panes/VTK.ipynb
  examples/reference/panes/VTKJS.ipynb
  panel/_package-lock.json
  panel/models/vtk.py
  panel/models/vtk/index.ts
  panel/models/vtk/panel_fullscreen_renwin_sync.ts
  panel/models/vtk/util.ts
  panel/models/vtk/vtk.ts
  panel/models/vtk/vtk_layout.ts
  panel/models/vtk/vtk_utils.ts
  panel/models/vtk/vtkaxes.ts
  panel/models/vtk/vtkcolorbar.ts
  panel/models/vtk/vtkjs.ts
  panel/models/vtk/vtklayout.ts
  panel/models/vtk/vtksynchronized.ts
  panel/models/vtk/vtkvolume.ts
  panel/pane/__init__.py
  panel/pane/vtk/__init__.py
  panel/pane/vtk/synchronizable_deserializer.py
  panel/pane/vtk/synchronizable_serializer.py
  panel/pane/vtk/vtk.py
  panel/pane/vtk/vtkjs_serializer.py
  panel/tests/pane/test_vtk.py
Labels: status: ready, type: enhancement

#1406 [VTK] Various fix
  panel/pane/vtk/synchronizable_serializer.py
  panel/pane/vtk/vtk.py
  panel/tests/pane/test_vtk.py
Labels: status: ready

#1409 [VTK Fix] Ensure camera change is emit after mouse interaction
  panel/models/vtk/vtklayout.ts
Labels: status: ready

#1319 Add support for serving static files
  examples/user_guide/Deploy_and_Export.ipynb
  panel/__main__.py
  panel/command/__init__.py
  panel/command/serve.py
  panel/io/server.py
  panel/tests/test_cli.py
  panel/tests/test_server.py
  setup.py
Labels: type: enhancement

#1181 Alert pane: Allows providing contextual feedback messages for typical user actions
  examples/reference/panes/Alert.ipynb
  panel/_styles/alerts.css
  panel/pane/__init__.py
  panel/pane/alert.py
  panel/tests/pane/test_alert.py
Labels: type: feature

#1448 Update Markdown.ipynb
  examples/reference/panes/Markdown.ipynb
Labels: type: docs

#1451 [VTK] add vtkFollower
  panel/models/vtk/util.ts
  panel/models/vtk/vtkfollower.ts
  panel/pane/vtk/synchronizable_deserializer.py
  panel/pane/vtk/synchronizable_serializer.py
  panel/tests/pane/test_vtk.py
Labels: status: ready

#1456 [VTK] findPokedRenderer correction
  panel/models/vtk/util.ts
  panel/models/vtk/vtkrenderwindowinteractor.ts
Labels: status: ready
