Repository holoviz/panel, pull requests merged in 2020-01, with the labels that each got.

#909 Added FileSelector widget
  examples/reference/widgets/CrossSelector.ipynb
  examples/reference/widgets/FileSelector.ipynb
  panel/tests/widgets/test_file_selector.py
  panel/viewable.py
  panel/widgets/__init__.py
  panel/widgets/base.py
  panel/widgets/file_selector.py
  panel/widgets/select.py
Labels: status: ready

#977 Add support for displaying callback errors and stdout in the notebook
  examples/user_guide/Overview.ipynb
  panel/config.py
  panel/io/state.py
  panel/pane/markup.py
  panel/tests/conftest.py
  panel/tests/test_config.py
  panel/util.py
  panel/viewable.py
  setup.py
Labels: type: enhancement

#944 pn.Param reference notebook
  .gitignore
  examples/reference/panes/Param.ipynb
Labels: type: docs

#1018 Set up flake8 and clean up bare except and other errors
  examples/user_guide/Deploy_and_Export.ipynb
  panel/cli.py
  panel/config.py
  panel/interact.py
  panel/io/embed.py
  panel/io/notebook.py
  panel/layout.py
  panel/links.py
  panel/pane/base.py
  panel/pane/holoviews.py
  panel/pane/markup.py
  panel/pane/plotly.py
  panel/pane/vtk/vtk.py
  panel/param.py
  panel/pipeline.py
  panel/template.py
  panel/tests/pane/test_holoviews.py
  panel/tests/pane/test_plotly.py
  panel/tests/pane/test_vega.py
  panel/tests/pane/test_vtk.py
  panel/tests/test_pipeline.py
  panel/tests/test_template.py
  panel/tests/util.py
  panel/util.py
  panel/viewable.py
  panel/widgets/input.py
  panel/widgets/select.py
  panel/widgets/tables.py
  setup.cfg
  setup.py
Labels: status: ready

#1022 VTK 3D multi slice
  examples/reference/panes/VTKVolume.ipynb
  panel/models/index.ts
  panel/models/vtk.py
  panel/models/vtk/vtk.ts
  panel/models/vtk/vtk_layout.ts
  panel/models/vtk/vtk_utils.ts
  panel/models/vtk/vtkvolume.ts
  panel/pane/vtk/enums.py
  panel/pane/vtk/vtk.py
  panel/tests/pane/test_vtk.py
Labels: status: ready

#1054 Improve VTK tests and coverage
  panel/pane/vtk/vtk.py
  panel/pane/vtk/vtkjs_serializer.py
  panel/tests/pane/test_vtk.py
  setup.py
Labels: status: ready
