Repository holoviz/panel, pull requests merged in 2020-08, with the labels that each got.

#1242 Filedownload example added
  examples/gallery/simple/file_download_examples.ipynb
Labels: status: ready

#1520 Expose auto_edit option on DataFrame table
  examples/reference/widgets/DataFrame.ipynb
  panel/widgets/tables.py
Labels: type: enhancement

#1524 Enabled disabled dates
  examples/reference/widgets/DatePicker.ipynb
  panel/widgets/input.py
Labels: status: ready

#1526 Add state.as_cached function
  examples/user_guide/Overview.ipynb
  panel/io/state.py
  panel/tests/io/test_state.py
Labels: type: enhancement

#1530 WIP adding React Grid Layout Template
  panel/template/__init__.py
  panel/template/base.py
  panel/template/react/__init__.py
  panel/template/react/dark.css
  panel/template/react/default.css
  panel/template/react/react.css
  panel/template/react/react.html
Labels: type: enhancement

#1540 Updated reference gallery [doc-build]
  examples/reference/panes/Alert.ipynb
  examples/reference/panes/Bokeh.ipynb
  examples/reference/panes/ECharts.ipynb
  examples/reference/panes/IPyWidget.ipynb
  examples/reference/panes/VTK.ipynb
  examples/reference/panes/VTKJS.ipynb
  examples/reference/panes/Vega.ipynb
  examples/reference/widgets/FileDownload.ipynb
  examples/reference/widgets/MenuButton.ipynb
Labels: type: docs

#1546 Support size argument on Select widget
  examples/reference/widgets/Select.ipynb
  panel/models/__init__.py
  panel/models/index.ts
  panel/models/singleselect.ts
  panel/models/widgets.py
  panel/widgets/__init__.py
  panel/widgets/select.py
Labels: type: enhancement

#1547 Ensure DataFrame with no index is editable
  panel/widgets/tables.py
Labels: status: ready

#1553 Fix for event ordering in CommManager
  panel/models/comm_manager.ts
Labels: status: ready
