Repository holoviz/panel, pull requests merged in 2020-09, with the labels that each got.

#1528 Add a number of ValueIndicators
  examples/reference/indicators/BooleanStatus.ipynb
  examples/reference/indicators/Dial.ipynb
  examples/reference/indicators/Gauge.ipynb
  examples/reference/indicators/LoadingSpinner.ipynb
  examples/reference/indicators/Number.ipynb
  examples/reference/indicators/Progress.ipynb
  panel/tests/test_docs.py
  panel/tests/widgets/test_base.py
  panel/tests/widgets/test_indicators.py
  panel/widgets/__init__.py
  panel/widgets/indicators.py
  panel/widgets/misc.py
Labels: type: enhancement

#1577 Wait until JS dependency is loaded before rendering
  panel/_templates/doc_nb_js.js
  panel/config.py
  panel/io/notebook.py
Labels: type: bug

#1576 added new example for gallery
  examples/gallery/dynamic/dynamic_timeseries_image_analysis.ipynb
Labels: type: docs

#1584 fixed issue 1581
  panel/param.py
  panel/tests/test_param.py
Labels: ready for review

#1590 Add String indicator
  panel/widgets/indicators.py
Labels: type: enhancement

#1595 Ensure panel.js is served before session is started
  panel/io/server.py
Labels: type: bug

#1594 Add Okta OAuth component
  examples/user_guide/Authentication.ipynb
  panel/auth.py
Labels: type: enhancement

#1385 Fixed typos
  README.md
  examples/user_guide/APIs.ipynb
  panel/pipeline.py
Labels: status: WIP
