Repository holoviz/panel, pull requests merged in 2021-11, with the labels that each got.

#2873 Add GenericLoginHandler for custom OAuth
  panel/auth.py
Labels: type: enhancement

#2875 Add quill.js based TextEditor widget
  examples/reference/widgets/TextEditor.ipynb
  panel/_templates/autoload_panel_js.js
  panel/config.py
  panel/dist/css/widgets.css
  panel/models/index.ts
  panel/models/quill.py
  panel/models/quill.ts
  panel/widgets/__init__.py
  panel/widgets/ace.py
  panel/widgets/texteditor.py
Labels: status: ready

#2893 Adds escape parameter to DataFrame pane to enable using html markup
  examples/reference/panes/DataFrame.ipynb
  panel/pane/markup.py
  panel/tests/pane/test_markup.py
Labels: ready for review

#2897 fix #2896: Colorbar background for dark theme
  panel/template/fast/theme.py
Labels: ready for review

#2902 Ensure stream and patch events do not boomerang
  panel/reactive.py
Labels: type: bug

#2931 Fix Tabulator checkbox selection
  panel/models/tabulator.ts
Labels: type: bug

#2961 Fix regression rendering HoloViews plotly backend
  panel/pane/holoviews.py
Labels: type: bug

#2964 Support async functions on ParamMethod/ParamFunction
  panel/param.py
Labels: type: enhancement
