Repository holoviz/panel, pull requests merged in 2021-03, with the labels that each got.

#2057 Fix jQuery import in BootstrapTemplate
  panel/template/bootstrap/__init__.py
Labels: type: bug

#2072 Allow setting horizontal and vertical alignment separately
  examples/user_guide/Customization.ipynb
  panel/viewable.py
Labels: type: enhancement

#2085 Fix value_throttled in pn.depends decorator
  panel/widgets/input.py
  panel/widgets/slider.py
Labels: ready for review

#1894 Add ReactiveHTML
  doc/user_guide/index.rst
  examples/user_guide/Custom_Components.ipynb
  panel/links.py
  panel/models/__init__.py
  panel/models/html.ts
  panel/models/index.ts
  panel/models/layout.ts
  panel/models/markup.py
  panel/models/reactive_html.py
  panel/models/reactive_html.ts
  panel/pane/markup.py
  panel/reactive.py
  panel/tests/test_reactive.py
  setup.py
Labels: status: ready

#2121 Add missing end tag in Templates
  panel/template/bootstrap/bootstrap.html
  panel/template/fast/grid/fast_grid_template.html
  panel/template/fast/list/fast_list_template.html
  panel/template/golden/golden.html
  panel/template/material/material.html
  panel/template/react/react.html
  panel/template/vanilla/vanilla.html
Labels: ready for review

#2123 Remove bootstrap css from FastGridTemplate
  panel/template/fast/base.py
Labels: ready for review

#2111 Add editable sliders
  examples/reference/widgets/EditableFloatSlider.ipynb
  examples/reference/widgets/EditableIntSlider.ipynb
  examples/reference/widgets/EditableRangeSlider.ipynb
  panel/dist/css/widgets.css
  panel/widgets/__init__.py
  panel/widgets/input.py
  panel/widgets/slider.py
Labels: type: enhancement
