Repository holoviz/panel, pull requests merged in 2021-02, with the labels that each got.

#1976 Update panel serve commandline argument docs
  examples/user_guide/Deploy_and_Export.ipynb
Labels: type: docs

#1880 SpeechToText Widget
  examples/gallery/simple/speech_to_text.ipynb
  examples/reference/widgets/SpeechToText.ipynb
  panel/models/index.ts
  panel/models/speech_to_text.py
  panel/models/speech_to_text.ts
  panel/tests/widgets/test_speech_to_text.py
  panel/widgets/__init__.py
  panel/widgets/button.py
  panel/widgets/speech_to_text.py
Labels: ready for review

#1937 Add link to installation instructions to getting started guide
  doc/index.rst
  examples/getting_started/Introduction.ipynb
Labels: status: ready

#1878 TextToSpeech Widget
  examples/reference/widgets/TextToSpeech.ipynb
  panel/models/index.ts
  panel/models/text_to_speech.py
  panel/models/text_to_speech.ts
  panel/tests/layout/test_spacer.py
  panel/tests/widgets/test_text_to_speech.py
  panel/viewable.py
  panel/widgets/__init__.py
  panel/widgets/text_to_speech.py
Labels: ready for review

#1997 Add .devcontainer to .gitignore
  .gitignore
Labels: ready for review

#1730 Panel loading indicator
  MANIFEST.in
  examples/gallery/param/loading_indicator.ipynb
  examples/gallery/simple/loading_param.ipynb
  examples/user_guide/Components.ipynb
  examples/user_guide/Customization.ipynb
  examples/user_guide/Overview.ipynb
  panel/assets/arc_spinner.svg
  panel/assets/arcs_spinner.svg
  panel/assets/bar_spinner.svg
  panel/assets/dots_spinner.svg
  panel/assets/petal_spinner.svg
  panel/config.py
  panel/dist/css/loading.css
  panel/dist/css/widgets.css
  panel/io/loading.py
  panel/io/model.py
  panel/io/resources.py
  panel/links.py
  panel/pane/base.py
  panel/param.py
  panel/reactive.py
  panel/template/theme/dark.css
  panel/tests/test_interact.py
  panel/tests/test_reactive.py
  panel/viewable.py
  panel/widgets/base.py
  panel/widgets/button.py
Labels: ready for review, status: ready

#2000 Adds the watch argument to pn.bind
  panel/depends.py
Labels: ready for review

#2021 Remove change of theme_toggle
  panel/template/fast/base.py
Labels: ready for review

#2032 Panel 0.11.0rc4: Auto Reload- Should not get a module_name not in sys.modules
  panel/io/reload.py
Labels: ready for review
