Repository holoviz/panel, pull requests merged in 2021-07, with the labels that each got.

#2425 improve Tabulator style for Fast Templates
  panel/dist/bundled/datatabulator/tabulator-tables@4.9.3/dist/css/fast/tabulator_fast.min.css
  panel/models/tabulator.py
  panel/models/tabulator.ts
  panel/template/base.py
  panel/template/fast/base.py
  panel/template/fast/css/fast_panel_widgets.css
  panel/widgets/tables.py
Labels: type: enhancement

#2488 Improve codehilite look and feel in Fast Templates
  panel/template/fast/css/fast_panel.css
Labels: ready for review

#2484 Fast template improvements
  examples/reference/templates/FastGridTemplate.ipynb
  examples/reference/templates/FastListTemplate.ipynb
  panel/template/fast/base.py
  panel/template/fast/grid/dark.css
  panel/template/fast/grid/default.css
  panel/template/fast/grid/fast_grid_template.css
  panel/template/fast/grid/fast_grid_template.html
  panel/template/fast/js/fast_template.js
  panel/template/fast/list/default.css
  panel/template/fast/list/fast_list_template.css
  panel/template/fast/list/fast_list_template.html
  panel/template/fast/theme.py
  panel/tests/template/fast/test_fast_grid_template.py
  panel/tests/template/fast/test_fast_list_template.py
Labels: ready for review

#2508 fix videostream unpause
  panel/models/videostream.ts
Labels: ready for review

#2521 Fix Perspective Filter Errors
  panel/pane/perspective.py
Labels: ready for review

#2555 Fix bug updating Tqdm indicator
  panel/widgets/indicators.py
Labels: type: bug

#2565 fix #2184: logo issue
  panel/template/fast/grid/fast_grid_template.html
  panel/template/fast/list/fast_list_template.html
Labels: ready for review

#2566 Fix #2560 theme_toggle
  examples/reference/templates/FastGridTemplate.ipynb
  examples/reference/templates/FastListTemplate.ipynb
Labels: ready for review

#2572 support packages in config of _autoload_js cf. #2571
  panel/io/notebook.py
Labels: ready for review

#2580 FastGridTemplate: Don't use persisted layout if save_layout=False
  panel/template/fast/grid/fast_grid_template.html
  panel/template/react/react.html
Labels: ready for review

#2587 Add streaming Trend indicator example
  examples/gallery/streaming/streaming_indicator.ipynb
  panel/models/trend.ts
Labels: type: docs
