Repository holoviz/panel, pull requests merged in 2021-12, with the labels that each got.

#2982 Sync URL location hash interactively
  panel/models/location.ts
Labels: type: enhancement

#2997 Ensure TemplateActions component does not have height
  panel/template/base.py
Labels: type: bug

#3035 mentions vega does not support responsive
  examples/reference/panes/Vega.ipynb
Labels: ready for review

#2986 Add alphabetical and custom sort to Param
  examples/user_guide/Param.ipynb
  panel/param.py
  panel/tests/test_param.py
Labels: ready for review

#3045 Fix Fast Vertical Slider CSS
  panel/template/fast/css/fast_bokeh.css
Labels: ready for review
