Repository holoviz/panel, pull requests merged in 2021-01, with the labels that each got.

#1875 ECharts depends on sliders fix
  panel/pane/echarts.py
  panel/tests/pane/test_echart.py
Labels: ready for review

#1877 Echarts sunburst fix
  panel/pane/echarts.py
Labels: ready for review

#1887 Support remote pagination sorting on Tabulator
  panel/models/tabulator.py
  panel/models/tabulator.ts
  panel/widgets/tables.py
Labels: type: bug

#1922 Correctly set up preprocessor on Template root
  panel/template/base.py
Labels: type: bug

#1892 Update charts example
  .github/workflows/docs.yaml
  .github/workflows/test.yaml
  examples/reference/panes/ECharts.ipynb
Labels: type: docs
