Repository holoviz/panel, pull requests merged in 2021-06, with the labels that each got.

#2183 Site Updates
  README.md
  doc/_static/logo_horizontal_light_theme.png
Labels: in progress

#2347 set jupyter_bokeh version to get vs code working
  setup.py
Labels: ready for review

#2303 Custom Colors in Fast Templates
  examples/reference/templates/FastGridTemplate.ipynb
  examples/reference/templates/FastListTemplate.ipynb
  panel/template/fast/base.py
  panel/template/fast/css/fast_root.css
  panel/template/fast/css/fast_root_dark.css
  panel/template/fast/css/fast_root_default.css
  panel/template/fast/grid/default.css
  panel/template/fast/grid/fast_grid_template.css
  panel/template/fast/grid/fast_grid_template.html
  panel/template/fast/list/default.css
  panel/template/fast/list/fast_list_template.css
  panel/template/fast/list/fast_list_template.html
  panel/template/fast/theme.py
  panel/tests/template/fast/test_fast_grid_template.py
  panel/tests/template/fast/test_fast_list_template.py
Labels: ready for review

#2357 Add save_layout and prevent_collision to FastGridTemplate
  examples/reference/templates/FastGridTemplate.ipynb
  panel/template/fast/grid/fast_grid_template.html
  panel/template/fast/list/fast_list_template.html
  panel/tests/template/fast/test_fast_grid_template.py
Labels: ready for review

#2090 Terminal Widget based on xtermjs
  examples/reference/widgets/Terminal.ipynb
  panel/_templates/doc_nb_js.js
  panel/config.py
  panel/models/index.ts
  panel/models/terminal.py
  panel/models/terminal.ts
  panel/tests/widgets/test_base.py
  panel/tests/widgets/test_terminal.py
  panel/widgets/__init__.py
  panel/widgets/terminal.py
  tox.ini
Labels: status: ready

#2378 add slider horizontal bar back
  panel/template/fast/css/fast_root.css
Labels: ready for review

#2385 Add parameters to Plotly reference guide
  examples/reference/panes/Plotly.ipynb
Labels: in progress

#2417 fix vertical scrollbar in fast templates
  panel/template/fast/css/fast_root.css
  panel/template/fast/grid/fast_grid_template.css
  panel/template/fast/list/fast_list_template.css
  panel/template/theme/dark.css
Labels: ready for review

#2437 Fix Card Header in Fast Templates
  panel/template/fast/css/fast_panel.css
Labels: ready for review

#2079 Tqdm Indicator
  examples/reference/indicators/Tqdm.ipynb
  panel/tests/widgets/test_base.py
  panel/tests/widgets/test_tqdm.py
  panel/widgets/__init__.py
  panel/widgets/indicators.py
  panel/widgets/tables.py
Labels: ready for review
