Repository holoviz/panel, pull requests merged in 2022-01, with the labels that each got.

#3040 fixes #3039: tqdm style color reset
  panel/tests/widgets/test_indicators.py
  panel/widgets/indicators.py
Labels: ready for review

#3055 Add py.typed file to support mypy
  MANIFEST.in
  panel/py.typed
Labels: ready for review

#3047 Fix .app method
  panel/io/server.py
Labels: ready for review

#2597 Implement built-in threading
  examples/user_guide/Deploy_and_Export.ipynb
  examples/user_guide/Overview.ipynb
  examples/user_guide/Performance_and_Debugging.ipynb
  panel/command/serve.py
  panel/config.py
  panel/io/callbacks.py
  panel/io/server.py
  panel/io/state.py
  panel/pane/vega.py
  panel/reactive.py
  panel/tests/conftest.py
  panel/tests/test_server.py
  panel/tests/widgets/test_button.py
  panel/tests/widgets/test_select.py
  panel/widgets/button.py
  panel/widgets/tables.py
  panel/widgets/terminal.py
  setup.py
Labels: type: feature

#3053 Adds autoplay and muted to media
  examples/reference/panes/Audio.ipynb
  examples/reference/panes/Video.ipynb
  panel/models/audio.ts
  panel/models/video.ts
  panel/models/widgets.py
  panel/pane/media.py
  panel/tests/pane/test_media.py
Labels: ready for review

#3118 Update Readme: remove comms mention and update binder version
  README.md
Labels: ready for review

#3032 Adds vega altair style example for the gallery.
  examples/gallery/styles/VegaAltairStyle.ipynb
  examples/homepage.ipynb
Labels: ready for review

#3036 Adds a matplotlib style guide notebook to gallery
  examples/gallery/styles/MatplotlibStyle.ipynb
Labels: ready for review

#3038 Adds Plotly styling gallery notebook
  examples/gallery/styles/PlotlyStyle.ipynb
Labels: ready for review

#1504 Set alignment of Widgets to ('start', 'end')
  panel/widgets/base.py
Labels: type: enhancement

#3158 Update and improve DeckGL pane
  examples/reference/panes/DeckGL.ipynb
  panel/models/deckgl.py
  panel/models/deckgl.ts
  panel/pane/deckgl.py
Labels: status: WIP
