Repository holoviz/panel, pull requests merged in 2023-04, with the labels that each got.

#4646 Update Panelite and Discord links
  CONTRIBUTING.MD
  README.md
  examples/developer_guide/Developing_Custom_Models.ipynb
Labels: status: ready

#4649 use panelite word
  doc/how_to/wasm/jupyterlite.md
Labels: status: ready, type: docs

#4645 Make it clear that download of pyodide dependencies only happens once
  doc/getting_started/build_app.md
Labels: status: ready

#4652 Improve intro example
  examples/homepage.ipynb
Labels: status: ready

#3679 Implement ability to reuse session for initial render
  panel/command/serve.py
  panel/config.py
  panel/io/server.py
  panel/io/state.py
  panel/tests/conftest.py
  panel/tests/test_server.py
  panel/tests/ui/io/test_server.py
Labels: type: enhancement

#4655 Feature/automated panelite tests
  .github/workflows/docs.yaml
  .github/workflows/jupyterlite.yaml
  .github/workflows/test.yaml
  .gitignore
  doc/how_to/callbacks/load.md
  doc/how_to/callbacks/periodic.md
  doc/how_to/custom_components/custom_reactiveHTML.md
  doc/how_to/custom_components/custom_viewer.md
  doc/how_to/custom_components/examples/canvas_draw.md
  doc/how_to/custom_components/examples/leaflet.md
  doc/how_to/layout/spacing.md
  doc/how_to/links/jscallbacks.md
  doc/how_to/links/jslinks.md
  doc/how_to/links/link_plots.md
  doc/how_to/links/links.md
  doc/how_to/links/watchers.md
  doc/how_to/param/custom.md
  doc/how_to/param/dependencies.md
  doc/how_to/param/examples/loading.md
  doc/how_to/param/subobjects.md
  doc/how_to/param/uis.md
  doc/how_to/styling/apply_css.md
  doc/how_to/styling/load_icon.md
  doc/how_to/styling/visibility.md
  examples/gallery/penguin_crossfilter.ipynb
  lite/files/Getting_Started.ipynb
  lite/files/README.md
  scripts/generate_panelite_content.py
  scripts/panelite/generate_panelite_content.json
  scripts/panelite/generate_panelite_content.py
  scripts/panelite/test/__init__.py
  scripts/panelite/test/failed_tests.txt
  scripts/panelite/test/notebooks_with_panelite_issues.py
  scripts/panelite/test/test_panelite.py
  scripts/panelite/test/test_utils.py
  scripts/panelite/test/utils.py
  scripts/panelite_dependencies.json
Labels: type: docs, panelite

#4699 Improve Markdown reference notebook
  examples/reference/panes/Markdown.ipynb
Labels: status: ready

#4709 Improve FloatPanel docs
  examples/reference/layouts/FloatPanel.ipynb
Labels: status: ready

#4722 Fix vtk_slicer
  examples/gallery/vtk_slicer.ipynb
Labels: status: ready

#4717 Minor improvements to home page
  doc/index.md
Labels: status: ready

#4738 Fix mimetype issue
  panel/io/resources.py
Labels: status: ready
