Repository holoviz/panel, pull requests merged in 2023-07, with the labels that each got.

#5112 Enhance defer load docs
  doc/how_to/callbacks/defer_load.md
  doc/how_to/callbacks/index.md
  doc/how_to/callbacks/load.md
Labels: status: ready

#5027 Streamlit migration Guide
  doc/_static/images/panel_dynamic_layout.png
  doc/_static/images/panel_hello_world.png
  doc/_static/images/panel_layout_example.png
  doc/_static/images/panel_markdown_example.png
  doc/_static/images/panel_mpl_example.png
  doc/_static/images/panel_widgets_example.png
  doc/_static/images/slides_dark.png
  doc/_static/images/slides_default.png
  doc/_static/images/streamlit_dymamic_layout.png
  doc/_static/images/streamlit_hello_world.png
  doc/_static/images/streamlit_layout_example.png
  doc/_static/images/streamlit_mpl_example.png
  doc/_static/images/streamlit_widgets_example.png
  doc/how_to/caching/manual.md
  doc/how_to/index.md
  doc/how_to/interactivity/bind_generators.md
  doc/how_to/migrate/streamlit/activity.md
  doc/how_to/migrate/streamlit/caching.md
  doc/how_to/migrate/streamlit/get_started.md
  doc/how_to/migrate/streamlit/index.md
  doc/how_to/migrate/streamlit/interactivity.md
  doc/how_to/migrate/streamlit/layouts.md
  doc/how_to/migrate/streamlit/multipage_apps.md
  doc/how_to/migrate/streamlit/panes.md
  doc/how_to/migrate/streamlit/session_state.md
  doc/how_to/migrate/streamlit/templates.md
  doc/how_to/migrate/streamlit/widgets.md
  doc/how_to/migrate_to_panel.md
  examples/reference/widgets/Button.ipynb
  examples/reference/widgets/FileDownload.ipynb
  examples/reference/widgets/Toggle.ipynb
  panel/io/cache.py
  panel/io/state.py
  panel/pane/base.py
  panel/widgets/button.py
Labels: status: ready

#5268 Fix dom events description
  doc/explanation/components/components_custom.md
Labels: ready for review

#5270 Make text widget value description more precise
  examples/reference/widgets/TextAreaInput.ipynb
  examples/reference/widgets/TextInput.ipynb
Labels: ready for review

#5263 fix broken link in Streamlit comparision
  doc/explanation/comparisons/compare_streamlit.md
Labels: ready for review

#5266 Document fast full screen mode
  examples/assets/FastGridTemplateFullScreen.png
  examples/assets/FastListTemplateFullScreen.png
  examples/reference/templates/FastGridTemplate.ipynb
  examples/reference/templates/FastListTemplate.ipynb
Labels: ready for review

#5257 Fix binder
  .gitignore
  binder/jupyter-panel-apps-server/examples-icon.svg
  binder/jupyter-voila-docs-server/__init__.py
  binder/jupyter-voila-docs-server/examples-icon.svg
  binder/jupyter-voila-docs-server/jupyter_voila_docs_server.py
  binder/jupyter-voila-docs-server/setup.py
  binder/postBuild
  binder/requirements.txt
  binder/start
  doc/developer_guide/index.md
  setup.py
Labels: ready for review

#5265 pdf fix
  panel/pane/image.py
  panel/tests/pane/test_image.py
  panel/tests/test_data/sample.pdf
Labels: ready for review

#5291 Fix video height issue
  panel/models/video.ts
Labels: ready for review

#5293 Mention Github star in Contributing Guide
  CONTRIBUTING.MD
Labels: ready for review

#5308 Update documentation with correct versions of panel
  doc/how_to/wasm/standalone.md
Labels: Sprint

#5306 [#2871] Improve interactive dataframes
  doc/how_to/interactivity/hvplot_interactive.md
Labels: Sprint

#5300 Simple enhancement of CONTRIBUTING guide
  CONTRIBUTING.MD
Labels: ready for review

#5311 Remove MyST inline directives from JupyterLite notebooks
  scripts/panelite/generate_panelite_content.py
Labels: type: docs

#5196 Add VS Code How To Guide
  .gitignore
  doc/_static/json/vscode-snippets-python.json
  doc/_static/terminal-breakpoint.png
  doc/_static/vscode-integrated-debugging.png
  doc/_static/vscode-notebook.png
  doc/_static/vscode-script.png
  doc/_static/vscode-snippets-python.png
  doc/how_to/editor/editor.md
  doc/how_to/editor/editor_debug.md
  doc/how_to/editor/index.md
  doc/how_to/editor/vscode_configure.md
  doc/how_to/notebook/other_nb.md
Labels: status: ready

#5296 fix video max-height
  panel/models/video.ts
Labels: ready for review

#5302 Update the example in the Build an App section of Getting Started
  doc/getting_started/build_app.md
Labels: Sprint

#4821 Add "missing" images to core concepts
  doc/_static/images/core_concepts_app.png
  doc/getting_started/core_concepts.md
Labels: status: ready, type: docs
