Repository holoviz/panel, pull requests merged in 2023-03, with the labels that each got.

#3168 Added explicit comparison to JS
  doc/background/comparisons.md
Labels: type: docs

#3007 Adds Swipe layout
  examples/reference/layouts/Swipe.ipynb
  panel/__init__.py
  panel/dist/css/swipe.css
  panel/layout/__init__.py
  panel/layout/swipe.py
  panel/tests/layout/test_swipe.py
  panel/tests/ui/layout/test_swipe.py
Labels: ready for review

#4350 add excel like editing example
  examples/gallery/demos/portfolio_analyser.py
Labels: in progress
