Repository holoviz/panel, pull requests merged in 2023-06, with the labels that each got.

#5019 Implement support for reactive generator functions
  doc/how_to/interactivity/bind_component.md
  doc/how_to/interactivity/bind_function.md
  doc/how_to/interactivity/bind_generators.md
  doc/how_to/interactivity/index.md
  panel/depends.py
  panel/layout/base.py
  panel/param.py
  panel/reactive.py
  panel/tests/test_param.py
  panel/tests/test_reactive.py
  setup.py
Labels: type: enhancement, api

#5068 Add missing docstring to TooltipIcon
  panel/widgets/indicators.py
Labels: status: ready

#5106 Ensure session arguments are correctly parsed by Jupyter executor
  panel/io/jupyter_executor.py
  panel/tests/ui/io/test_jupyter_server_extension.py
Labels: type: bug

#5087 Perspective make over
  examples/assets/perspective_edit.png
  examples/reference/panes/Perspective.ipynb
Labels: status: ready
