Repository holoviz/panel, pull requests merged in 2023-01, with the labels that each got.

#4047 Add Gallery VideoStream example
  .gitignore
  examples/assets/VideoStreamInterface.jpg
  examples/assets/VideoStreamInterfaceFaceDetectionViewer.jpg
  examples/assets/VideoStreamInterfaceSobel.jpg
  examples/assets/VideoStreamInterfaceTimer.jpg
  examples/gallery/streaming/streaming_videostream.ipynb
  setup.py
Labels: status: ready, in progress, webassembly

#4244 How to test Panel data apps
  doc/how_to/index.md
  doc/how_to/test/loadtests.md
  doc/how_to/test/pytest.md
  doc/how_to/test/uitests.md
  panel/io/state.py
  panel/tests/conftest.py
Labels: status: ready

#2949 Add Vue.js Custom Component Example
  examples/assets/VuePdbInput.gif
  examples/assets/vue_bootstrap_component.png
  examples/gallery/components/VuePdbInput.ipynb
Labels: ready for review

#4259 Add loading_indicator to global config
  doc/api/config.md
  panel/config.py
  panel/param.py
  panel/tests/test_param.py
Labels: status: ready

#4264 Improve README
  README.md
Labels: status: ready

#4262 Add contributing guide
  CONTRIBUTING.MD
  README.md
Labels: status: ready

#4292 Ensure Tabulator internal _index_mapping is updated on stream
  panel/tests/ui/widgets/test_tabulator.py
  panel/tests/widgets/test_tables.py
  panel/widgets/tables.py
Labels: type: bug, component: tabulator

#4296 Ensure updates to Tabulator formatter or editor updates model
  panel/models/tabulator.ts
  panel/tests/widgets/test_tables.py
  panel/widgets/tables.py
Labels: type: bug, component: tabulator

#4320 Upgrade plotly js
  panel/models/plotly.py
Labels: status: ready

#4355 Fix plotly eventdata undefined val
  panel/models/plotly.ts
Labels: status: ready
