Repository holoviz/panel, pull requests merged in 2024-03, with the labels that each got.

#6406 Preliminary cleanup of the TS codebase
  panel/eslint.js
  panel/models/ace.ts
  panel/models/audio.ts
  panel/models/browser.ts
  panel/models/button.ts
  panel/models/button_icon.ts
  panel/models/card.ts
  panel/models/checkbox_button_group.ts
  panel/models/column.ts
  panel/models/comm_manager.ts
  panel/models/customselect.ts
  panel/models/data.ts
  panel/models/datetime_picker.ts
  panel/models/deckgl.ts
  panel/models/echarts.ts
  panel/models/event-to-object.ts
  panel/models/feed.ts
  panel/models/file_download.ts
  panel/models/html.ts
  panel/models/icon.ts
  panel/models/ipywidget.ts
  panel/models/json.ts
  panel/models/jsoneditor.ts
  panel/models/katex.ts
  panel/models/layout.ts
  panel/models/location.ts
  panel/models/mathjax.ts
  panel/models/pdf.ts
  panel/models/perspective.ts
  panel/models/player.ts
  panel/models/plotly.ts
  panel/models/progress.ts
  panel/models/quill.ts
  panel/models/radio_button_group.ts
  panel/models/reactive_html.ts
  panel/models/singleselect.ts
  panel/models/speech_to_text.ts
  panel/models/state.ts
  panel/models/tabs.ts
  panel/models/tabulator.ts
  panel/models/terminal.ts
  panel/models/text_to_speech.ts
  panel/models/textarea_input.ts
  panel/models/toggle_icon.ts
  panel/models/tooltip_icon.ts
  panel/models/tooltips.ts
  panel/models/trend.ts
  panel/models/util.ts
  panel/models/vega.ts
  panel/models/video.ts
  panel/models/videostream.ts
  panel/models/vizzu.ts
  panel/models/vtk/vtkaxes.ts
  panel/models/vtk/vtkjs.ts
  panel/models/vtk/vtklayout.ts
  panel/models/vtk/vtksynchronized.ts
  panel/models/vtk/vtkvolume.ts
  panel/tsconfig.json
Labels: status: ready

#6454 Replace typeof with bokehjs' type queries
  panel/models/data.ts
  panel/models/deckgl.ts
  panel/models/plotly.ts
  panel/models/reactive_html.ts
  panel/models/tabulator.ts
  panel/models/tooltips.ts
  panel/models/util.ts
Labels: status: ready

#6422 Improve home page
  doc/getting_started/core_concepts.md
  doc/index.md
Labels: ready for review

#6467 Update Streamlit comparision
  doc/explanation/comparisons/compare_streamlit.md
Labels: ready for review

#6465 Normalize connection of signals
  examples/developer_guide/Developing_Custom_Models.ipynb
  panel/models/ace.ts
  panel/models/audio.ts
  panel/models/customselect.ts
  panel/models/datetime_picker.ts
  panel/models/deckgl.ts
  panel/models/echarts.ts
  panel/models/file_download.ts
  panel/models/html.ts
  panel/models/katex.ts
  panel/models/location.ts
  panel/models/mathjax.ts
  panel/models/perspective.ts
  panel/models/player.ts
  panel/models/plotly.ts
  panel/models/progress.ts
  panel/models/quill.ts
  panel/models/reactive_html.ts
  panel/models/singleselect.ts
  panel/models/speech_to_text.ts
  panel/models/tabulator.ts
  panel/models/terminal.ts
  panel/models/text_to_speech.ts
  panel/models/trend.ts
  panel/models/vega.ts
  panel/models/video.ts
  panel/models/videostream.ts
  panel/models/vizzu.ts
  panel/models/vtk/vtkjs.ts
  panel/models/vtk/vtksynchronized.ts
  panel/models/vtk/vtkvolume.ts
Labels: status: ready

#6493 Finalize basic cleanup of TS codebase and enable linting in pre-commit
  .pre-commit-config.yaml
  panel/eslint.js
  panel/models/chatarea_input.ts
  panel/models/comm_manager.ts
  panel/models/echarts.ts
  panel/models/event-to-object.ts
  panel/models/icon.ts
  panel/models/layout.ts
  panel/models/perspective.ts
  panel/models/reactive_html.ts
  panel/models/tabulator.ts
  panel/models/trend.ts
  panel/models/vizzu.ts
  panel/models/vtk/panel_fullscreen_renwin_sync.ts
  panel/models/vtk/util.ts
  panel/models/vtk/vtkaxes.ts
  panel/models/vtk/vtkcolorbar.ts
  panel/models/vtk/vtkjs.ts
  panel/models/vtk/vtklayout.ts
  panel/models/vtk/vtksynchronized.ts
  panel/models/vtk/vtkvolume.ts
  panel/package-lock.json
  panel/package.json
Labels: status: WIP

#6438 Rewrite `models/video.ts` and support CSS modules
  .gitignore
  panel/models/video.ts
  panel/models/widgets.py
  panel/styles/models/video.less
  panel/tsconfig.json
Labels: status: ready

#6491 Add intermediate Todo App tutorial
  doc/tutorials/intermediate/build_todo.md
  doc/tutorials/intermediate/index.md
  doc/tutorials/intermediate/test_todo.md
Labels: ready for review

#6466 Mature intermediate tutorials
  doc/tutorials/intermediate/build_todo.md
  doc/tutorials/intermediate/index.md
  doc/tutorials/intermediate/interactivity.md
  doc/tutorials/intermediate/param.md
  doc/tutorials/intermediate/parameters.md
  doc/tutorials/intermediate/reusable_components.md
  doc/tutorials/intermediate/structure_data_store.md
  doc/tutorials/intermediate/test_todo.md
Labels: ready for review

#6511 Add logging how-to guide
  doc/how_to/configure_logging.md
  doc/how_to/index.md
Labels: ready for review

#6525 How-to Configure PyCharm Guide
  doc/_static/images/pycharm-configure-panel.png
  doc/_static/images/pycharm-debug-panel.png
  doc/_static/images/pycharm-run-panel.png
  doc/_static/images/pycharm-serve-panel.png
  doc/how_to/editor/index.md
  doc/how_to/editor/pycharm_configure.md
Labels: ready for review

#6425 Finalize Basic Tutorials
  doc/_static/bar_chart_race.mp4
  doc/tutorials/basic/build_animation.md
  doc/tutorials/basic/build_todo.md
  doc/tutorials/basic/index.md
  doc/tutorials/basic/indicators_performance.md
  doc/tutorials/basic/panes.md
  doc/tutorials/basic/pn_bind.md
  doc/tutorials/basic/pn_rx.md
  doc/tutorials/basic/state.md
Labels: in progress, need input from Philipp

#6602 Fix layout persistence issues in dashboard builder
  panel/io/handlers.py
  panel/pane/vega.py
  panel/template/editable/__init__.py
  panel/template/editable/editable.html
Labels: in progress

#6601 Improve layout builder docs
  doc/_static/images/builder_reset_layout.png
  doc/_static/images/builder_save_layout.png
  doc/how_to/notebook/layout_builder.md
  panel/template/editable/editable.css
  panel/template/editable/editable.html
Labels: ready for review
