Repository holoviz/panel, pull requests merged in 2024-09, with the labels that each got.

#7017 Describe usage of pyscript editor
  doc/how_to/wasm/convert.md
  doc/how_to/wasm/standalone.md
  panel/command/convert.py
Labels: ready for review

#7224 Make --dev an alias for --autoreload
  doc/explanation/develop_seamlessly.md
  doc/getting_started/build_app.md
  doc/getting_started/core_concepts.md
  doc/getting_started/installation.md
  doc/how_to/server/commandline.md
  doc/how_to/streamlit_migration/get_started.md
  doc/how_to/wasm/convert.md
  doc/tutorials/basic/build_animation.md
  doc/tutorials/basic/build_chatbot.md
  doc/tutorials/basic/build_crossfilter_dashboard.md
  doc/tutorials/basic/build_image_classifier.md
  doc/tutorials/basic/build_monitoring_dashboard.md
  doc/tutorials/basic/build_streaming_dashboard.md
  doc/tutorials/basic/build_todo.md
  doc/tutorials/basic/caching.md
  doc/tutorials/basic/design.md
  doc/tutorials/basic/develop_editor.md
  doc/tutorials/basic/indicators_activity.md
  doc/tutorials/basic/indicators_performance.md
  doc/tutorials/basic/layouts.md
  doc/tutorials/basic/panes.md
  doc/tutorials/basic/pn_panel.md
  doc/tutorials/basic/progressive_layouts.md
  doc/tutorials/basic/serve.md
  doc/tutorials/basic/size.md
  doc/tutorials/basic/style.md
  doc/tutorials/basic/templates.md
  doc/tutorials/basic/widgets.md
  doc/tutorials/expert/custom_components.md
  doc/tutorials/intermediate/develop_editor.md
  doc/tutorials/intermediate/serve.md
  doc/tutorials/intermediate/structure_data_store.md
  panel/command/serve.py
  pyproject.toml
Labels: api

#7127 Docs review
  doc/developer_guide/index.md
  doc/explanation/components/reactive_html_components.md
  doc/how_to/custom_components/esm/callbacks.md
  doc/how_to/custom_components/esm/custom_layout.md
  doc/how_to/custom_components/esm/custom_widgets.md
  doc/how_to/custom_components/esm/dataframe.md
  doc/how_to/custom_components/examples/esm_leaflet.md
  doc/how_to/custom_components/index.md
  doc/how_to/custom_components/reactive_html/reactive_html_callbacks.md
  doc/how_to/migrate/anywidget/index.md
  doc/how_to/param/custom.md
  doc/tutorials/basic/layouts.md
  doc/tutorials/expert/custom_anywidget_components.md
  doc/tutorials/expert/custom_js_components.md
  doc/tutorials/expert/index.md
  examples/reference/chat/ChatAreaInput.ipynb
  examples/reference/chat/ChatMessage.ipynb
  examples/reference/custom_components/AnyWidgetComponent.ipynb
  examples/reference/layouts/Accordion.ipynb
  examples/reference/layouts/GridSpec.ipynb
  examples/reference/layouts/Swipe.ipynb
  examples/reference/panes/Param.ipynb
  panel/layout/spacer.py
Labels: ready for review

#7233 Fix cache.clear mypy issue
  panel/io/cache.py
Labels: ready for review

#7183 Add pycafe deployment guide
  doc/_static/logos/pycafe.png
  doc/how_to/deployment/index.md
  doc/how_to/deployment/pycafe.md
  doc/tutorials/basic/build_todo.md
Labels: in progress, need input from Philipp

#7271 Update pycafe username
  doc/how_to/deployment/pycafe.md
Labels: ready for review

#7278 Support panel fastapi behind reverse proxy
  panel/io/location.py
  panel/tests/io/test_location.py
Labels: need input from Philipp

#7043 New user feedback
  doc/_static/images/vscode-no-output-try-again.png
  doc/conf.py
  doc/explanation/api/examples/outliers_declarative.md
  doc/getting_started/build_app.md
  doc/how_to/editor/vscode_configure.md
  examples/assets/panel-sympy.png
  examples/reference/panes/LaTeX.ipynb
  examples/reference/panes/Vizzu.ipynb
  panel/models/vizzu.py
  panel/pane/equation.py
  panel/tests/ui/pane/test_vizzu.py
Labels: ready for review

#7273 Various pre 1.5.0 fixes
  doc/developer_guide/index.md
  doc/how_to/deployment/pycafe.md
  doc/tutorials/basic/index.md
  doc/tutorials/expert/custom_anywidget_components.md
  doc/tutorials/intermediate/index.md
Labels: ready for review

#7291 Document Tabulator Styling with Matplotlib gradients
  examples/reference/widgets/Tabulator.ipynb
Labels: ready for review

#7285 Collection of minor fixes for Panel 1.5.1
  doc/explanation/api/examples/outliers_declarative.md
  doc/explanation/comparisons/compare_streamlit.md
  doc/getting_started/core_concepts.md
  doc/how_to/concurrency/manual_threading.md
  doc/how_to/custom_components/esm/build.md
  doc/how_to/deployment/pycafe.md
  doc/how_to/editor/markdown.md
  doc/how_to/editor/vscode_configure.md
  doc/how_to/templates/template_arrange.md
  doc/how_to/templates/template_modal.md
  doc/how_to/templates/template_theme.md
  doc/tutorials/basic/develop_notebook.md
  doc/tutorials/expert/custom_anywidget_components.md
  examples/reference/custom_components/AnyWidgetComponent.ipynb
  examples/reference/custom_components/JSComponent.ipynb
  examples/reference/custom_components/ReactComponent.ipynb
  panel/__init__.py
  panel/command/serve.py
  panel/io/reload.py
Labels: ready for review

#7317 fastapi docs
  doc/how_to/integrations/FastAPI.md
  pyproject.toml
Labels: ready for review

#7346 Improve plotly style guide
  doc/how_to/styling/plotly.md
  examples/reference/panes/Plotly.ipynb
  panel/io/state.py
Labels: ready for review

#7342 Fix custom component docstrings
  panel/custom.py
Labels: ready for review
