Repository holoviz/panel, pull requests merged in 2024-05, with the labels that each got.

#6527 Rewrite `panel/models/reactive_html.ts`
  panel/models/comm_manager.ts
  panel/models/html.ts
  panel/models/layout.ts
  panel/models/pdf.ts
  panel/models/reactive_html.ts
Labels: status: ready

#6830 Propagate message params on send/stream methods
  examples/reference/chat/ChatFeed.ipynb
  panel/chat/feed.py
  panel/tests/chat/test_feed.py
Labels: type: enhancement

#6790 Implement Placeholder pane
  examples/reference/panes/Placeholder.ipynb
  panel/pane/__init__.py
  panel/pane/placeholder.py
  panel/tests/pane/test_placeholder.py
Labels: type: feature

#6847 Fix bug when perspective has not been rendered
  panel/models/perspective.ts
Labels: status: ready
