Repository holoviz/panel, pull requests merged in 2025-01, with the labels that each got.

#7587 Fix azure oauth issues
  panel/auth.py
  panel/command/__init__.py
  panel/tests/test_auth.py
Labels: ready for review

#7559 Add ChatMessage & ChatFeed edit functionality
  CHANGELOG.md
  doc/about/releases.md
  examples/reference/chat/ChatAreaInput.ipynb
  examples/reference/chat/ChatFeed.ipynb
  examples/reference/chat/ChatMessage.ipynb
  panel/chat/feed.py
  panel/chat/input.py
  panel/chat/interface.py
  panel/chat/message.py
  panel/dist/css/chat_message.css
  panel/tests/chat/test_feed.py
  panel/tests/chat/test_interface.py
  panel/tests/chat/test_message.py
  panel/tests/ui/chat/test_chat_interface_ui.py
Labels: type: feature

#7558 Add custom callback exception callable
  CHANGELOG.md
  doc/about/releases.md
  examples/reference/chat/ChatFeed.ipynb
  panel/chat/_param.py
  panel/chat/feed.py
  panel/tests/chat/test_feed.py
  panel/tests/chat/test_interface.py
Labels: type: enhancement

#7568 Add form tutorial
  doc/tutorials/intermediate/create_form.md
  doc/tutorials/intermediate/index.md
Labels: ready for review
